-- =====================================================
-- SEQUENCE
-- =====================================================

CREATE SEQUENCE SEQ_USER_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REPORT_CATEGORY_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ITEM_CATEGORY_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NOTI_CD_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BOARD_CATEGORY_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BOARD_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REPLY_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BOARD_IMG_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ITEM_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ITEM_IMG_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BID_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RESULT_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DELIVERY_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DELIVERY_DETAIL_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PAY_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NOTI_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REPORT_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AUTH_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SANCTION_NO START WITH 1 INCREMENT BY 1;

-- =====================================================
-- TABLE + COMMENT
-- =====================================================

CREATE TABLE AUTHORITIES (
AUTHORITY NUMBER PRIMARY KEY,
AUTHORITY_NAME VARCHAR2(20) DEFAULT 'USER' NOT NULL
);

COMMENT ON COLUMN AUTHORITIES.AUTHORITY IS '권한 번호 (1, 2, 3)';
COMMENT ON COLUMN AUTHORITIES.AUTHORITY_NAME IS '권한 이름';

CREATE TABLE MEMBER (
USER_NO NUMBER PRIMARY KEY,
AUTHORITY NUMBER NOT NULL,
USER_ID VARCHAR2(20) NOT NULL,
USER_PWD VARCHAR2(100) NOT NULL,
USER_NAME VARCHAR2(20) NOT NULL,
USER_ADDRESS VARCHAR2(100),
USER_PHONE VARCHAR2(15),
USER_EMAIL VARCHAR2(30),
USER_ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
USER_DELETE_YN VARCHAR2(1) DEFAULT 'N' NOT NULL,
USER_LOGIN_IP VARCHAR2(15),
LIKE_COUNT NUMBER DEFAULT 0 NOT NULL,
NO_PAY_COUNT NUMBER DEFAULT 0 NOT NULL
);

COMMENT ON COLUMN MEMBER.USER_NO IS '회원 번호';
COMMENT ON COLUMN MEMBER.AUTHORITY IS '권한 번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '이름';
COMMENT ON COLUMN MEMBER.USER_ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.USER_PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.USER_EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.USER_ENROLL_DATE IS '가입일';
COMMENT ON COLUMN MEMBER.USER_DELETE_YN IS '탈퇴 여부';
COMMENT ON COLUMN MEMBER.USER_LOGIN_IP IS '로그인 IP';
COMMENT ON COLUMN MEMBER.LIKE_COUNT IS '좋아요 수';
COMMENT ON COLUMN MEMBER.NO_PAY_COUNT IS '미결제 횟수';

CREATE TABLE ITEM_CD (
ITEM_CATEGORY_NO NUMBER PRIMARY KEY,
ITEM_CATEGORY VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN ITEM_CD.ITEM_CATEGORY_NO IS '상품 카테고리 번호';
COMMENT ON COLUMN ITEM_CD.ITEM_CATEGORY IS '상품 카테고리명';

CREATE TABLE BOARD_CATEGORY (
BOARD_CATEGORY_NO NUMBER PRIMARY KEY,
BOARD_CATEGORY VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN BOARD_CATEGORY.BOARD_CATEGORY_NO IS '게시판 카테고리 번호';
COMMENT ON COLUMN BOARD_CATEGORY.BOARD_CATEGORY IS '게시판 카테고리명';

CREATE TABLE REPORT_CATEGORY (
REPORT_CATEGORY_NO NUMBER PRIMARY KEY,
REPORT_CATEGORY VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN REPORT_CATEGORY.REPORT_CATEGORY_NO IS '신고 카테고리 번호';
COMMENT ON COLUMN REPORT_CATEGORY.REPORT_CATEGORY IS '신고 유형';

CREATE TABLE NOTI_CD (
NOTI_CATEGORY_NO NUMBER PRIMARY KEY,
NOTI_CATEGORY VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN NOTI_CD.NOTI_CATEGORY_NO IS '알림 카테고리 번호';
COMMENT ON COLUMN NOTI_CD.NOTI_CATEGORY IS '알림 유형';

CREATE TABLE COUNTRY (
COUNTRY_NO VARCHAR2(3) PRIMARY KEY,
COUNTRY VARCHAR2(30) DEFAULT '대한민국' NOT NULL
);

COMMENT ON COLUMN COUNTRY.COUNTRY_NO IS '국가 코드';
COMMENT ON COLUMN COUNTRY.COUNTRY IS '국가명';

CREATE TABLE ITEM (
ITEM_NO NUMBER PRIMARY KEY,
ITEM_CD_NO NUMBER NOT NULL,
USER_NO NUMBER NOT NULL,
ITEM_TITLE VARCHAR2(50) NOT NULL,
ITEM_SIZE NUMBER DEFAULT 10 NOT NULL,
ITEM_CONTENT VARCHAR2(200) NOT NULL,
START_PRICE NUMBER DEFAULT 0 NOT NULL,
DIRECT_BUY VARCHAR2(1) DEFAULT 'N' NOT NULL,
BUY_NOW_PRICE NUMBER,
CURRENT_PRICE NUMBER,
START_TIME DATE DEFAULT SYSDATE NOT NULL,
END_TIME DATE DEFAULT SYSDATE + 5 NOT NULL,
STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL,
CREATE_AT DATE DEFAULT SYSDATE NOT NULL,
COUNTRY_NO VARCHAR2(3) NOT NULL,
DELIVERY_NO NUMBER
);

COMMENT ON COLUMN ITEM.ITEM_NO IS '상품 번호';
COMMENT ON COLUMN ITEM.ITEM_CD_NO IS '상품 카테고리';
COMMENT ON COLUMN ITEM.USER_NO IS '판매자 번호';
COMMENT ON COLUMN ITEM.ITEM_TITLE IS '상품명';
COMMENT ON COLUMN ITEM.ITEM_SIZE IS '이미지 개수';
COMMENT ON COLUMN ITEM.ITEM_CONTENT IS '상품 설명';
COMMENT ON COLUMN ITEM.START_PRICE IS '시작가';
COMMENT ON COLUMN ITEM.DIRECT_BUY IS '즉시구매 여부';
COMMENT ON COLUMN ITEM.BUY_NOW_PRICE IS '즉시구매가';
COMMENT ON COLUMN ITEM.CURRENT_PRICE IS '현재가';
COMMENT ON COLUMN ITEM.START_TIME IS '시작 시간';
COMMENT ON COLUMN ITEM.END_TIME IS '종료 시간';
COMMENT ON COLUMN ITEM.STATUS IS '상태(Y/N/E)';
COMMENT ON COLUMN ITEM.CREATE_AT IS '등록일';
COMMENT ON COLUMN ITEM.COUNTRY_NO IS '국가 코드';
COMMENT ON COLUMN ITEM.DELIVERY_NO IS '배송 번호';

CREATE TABLE ITEM_IMG (
ITEM_IMG_NO NUMBER PRIMARY KEY,
ITEM_NO NUMBER NOT NULL,
IMG_URL VARCHAR2(200) NOT NULL
);

COMMENT ON COLUMN ITEM_IMG.ITEM_IMG_NO IS '이미지 번호';
COMMENT ON COLUMN ITEM_IMG.ITEM_NO IS '상품 번호';
COMMENT ON COLUMN ITEM_IMG.IMG_URL IS '이미지 URL';

CREATE TABLE BID (
BID_NO NUMBER PRIMARY KEY,
ITEM_NO NUMBER NOT NULL,
USER_NO NUMBER NOT NULL,
BID_PRICE NUMBER,
BID_TIME DATE DEFAULT SYSDATE NOT NULL,
RANKING NUMBER
);

COMMENT ON COLUMN BID.BID_NO IS '입찰 번호';
COMMENT ON COLUMN BID.ITEM_NO IS '상품 번호';
COMMENT ON COLUMN BID.USER_NO IS '입찰자';
COMMENT ON COLUMN BID.BID_PRICE IS '입찰 금액';
COMMENT ON COLUMN BID.BID_TIME IS '입찰 시간';
COMMENT ON COLUMN BID.RANKING IS '순위';

CREATE TABLE RESULT (
RESULT_NO NUMBER PRIMARY KEY,
BID_NO NUMBER NOT NULL,
FINAL_PRICE NUMBER,
RESULT_TIME DATE DEFAULT SYSDATE NOT NULL,
STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL
);

COMMENT ON COLUMN RESULT.RESULT_NO IS '결과 번호';
COMMENT ON COLUMN RESULT.BID_NO IS '입찰 번호';
COMMENT ON COLUMN RESULT.FINAL_PRICE IS '낙찰가';
COMMENT ON COLUMN RESULT.RESULT_TIME IS '결과 시간';
COMMENT ON COLUMN RESULT.STATUS IS '상태';

CREATE TABLE PAYMENT (
PAYMENT_NO NUMBER PRIMARY KEY,
RESULT_NO NUMBER NOT NULL,
PAYMENT_METHOD VARCHAR2(20),
PAYMENT_STATUS VARCHAR2(1) DEFAULT 'N',
PAYMENT_TIME DATE DEFAULT SYSDATE NOT NULL,
PAY_CODE VARCHAR2(20)
);

COMMENT ON COLUMN PAYMENT.PAYMENT_NO IS '결제 번호';
COMMENT ON COLUMN PAYMENT.RESULT_NO IS '결과 번호';
COMMENT ON COLUMN PAYMENT.PAYMENT_METHOD IS '결제 방식';
COMMENT ON COLUMN PAYMENT.PAYMENT_STATUS IS '결제 상태';
COMMENT ON COLUMN PAYMENT.PAYMENT_TIME IS '결제 시간';
COMMENT ON COLUMN PAYMENT.PAY_CODE IS '결제 코드';

CREATE TABLE DELIVERY (
DELIVERY_NO NUMBER PRIMARY KEY,
PAYMENT_NO NUMBER NOT NULL,
BUYER_ID NUMBER NOT NULL,
SELLER_ID NUMBER NOT NULL,
RECEIVER_NAME VARCHAR2(20) NOT NULL,
RECEIVER_PHONE VARCHAR2(15) NOT NULL,
POST_CODE VARCHAR2(10) NOT NULL,
ADDRESS VARCHAR2(200) NOT NULL,
ADDRESS_DETAIL VARCHAR2(200) NOT NULL,
DELIVERY_REQUEST VARCHAR2(200),
COURIER VARCHAR2(50),
TRACKING_NO VARCHAR2(50)
);

COMMENT ON COLUMN DELIVERY.DELIVERY_NO IS '배송 번호';
COMMENT ON COLUMN DELIVERY.PAYMENT_NO IS '결제 번호';
COMMENT ON COLUMN DELIVERY.BUYER_ID IS '구매자';
COMMENT ON COLUMN DELIVERY.SELLER_ID IS '판매자';
COMMENT ON COLUMN DELIVERY.RECEIVER_NAME IS '수령인';
COMMENT ON COLUMN DELIVERY.RECEIVER_PHONE IS '전화번호';
COMMENT ON COLUMN DELIVERY.POST_CODE IS '우편번호';
COMMENT ON COLUMN DELIVERY.ADDRESS IS '주소';
COMMENT ON COLUMN DELIVERY.ADDRESS_DETAIL IS '상세주소';
COMMENT ON COLUMN DELIVERY.DELIVERY_REQUEST IS '요청사항';
COMMENT ON COLUMN DELIVERY.COURIER IS '택배사';
COMMENT ON COLUMN DELIVERY.TRACKING_NO IS '운송장번호';

CREATE TABLE DELIVERY_DETAIL (
DELIVERY_DETAIL_NO NUMBER PRIMARY KEY,
DELIVERY_NO NUMBER NOT NULL,
STATUS VARCHAR2(20),
SHIPPED_DATE DATE,
DELIVERED_DATE DATE
);

COMMENT ON COLUMN DELIVERY_DETAIL.DELIVERY_DETAIL_NO IS '배송상세 번호';
COMMENT ON COLUMN DELIVERY_DETAIL.DELIVERY_NO IS '배송 번호';
COMMENT ON COLUMN DELIVERY_DETAIL.STATUS IS '배송 상태';
COMMENT ON COLUMN DELIVERY_DETAIL.SHIPPED_DATE IS '발송일';
COMMENT ON COLUMN DELIVERY_DETAIL.DELIVERED_DATE IS '도착일';

CREATE TABLE BOARD_POST (
BOARD_NO NUMBER PRIMARY KEY,
BOARD_CD_NO NUMBER NOT NULL,
USER_NO NUMBER NOT NULL,
BOARD_TITLE VARCHAR2(100) NOT NULL,
BOARD_CONTENT VARCHAR2(4000) NOT NULL,
BOARD_DATE DATE DEFAULT SYSDATE NOT NULL,
VIEW_COUNT NUMBER DEFAULT 0,
BOARD_DELETE VARCHAR2(1) DEFAULT 'N' NOT NULL
);

COMMENT ON COLUMN BOARD_POST.BOARD_NO IS '게시글 번호';
COMMENT ON COLUMN BOARD_POST.BOARD_CD_NO IS '카테고리';
COMMENT ON COLUMN BOARD_POST.USER_NO IS '작성자';
COMMENT ON COLUMN BOARD_POST.BOARD_TITLE IS '제목';
COMMENT ON COLUMN BOARD_POST.BOARD_CONTENT IS '내용';
COMMENT ON COLUMN BOARD_POST.BOARD_DATE IS '작성일';
COMMENT ON COLUMN BOARD_POST.VIEW_COUNT IS '조회수';
COMMENT ON COLUMN BOARD_POST.BOARD_DELETE IS '삭제 여부';

CREATE TABLE BOARD_IMG (
BOARD_IMG_NO NUMBER PRIMARY KEY,
BOARD_NO NUMBER NOT NULL,
IMG_LEVEL VARCHAR2(1) DEFAULT 'N' NOT NULL,
ORIGIN_NAME VARCHAR2(200) NOT NULL,
CHANGE_NAME VARCHAR2(500) NOT NULL
);

COMMENT ON COLUMN BOARD_IMG.BOARD_IMG_NO IS '이미지 번호';
COMMENT ON COLUMN BOARD_IMG.BOARD_NO IS '게시글 번호';
COMMENT ON COLUMN BOARD_IMG.IMG_LEVEL IS '대표 여부';
COMMENT ON COLUMN BOARD_IMG.ORIGIN_NAME IS '원본명';
COMMENT ON COLUMN BOARD_IMG.CHANGE_NAME IS '변경명';

CREATE TABLE REPLY (
REPLY_NO NUMBER PRIMARY KEY,
BOARD_NO NUMBER NOT NULL,
USER_NO NUMBER NOT NULL,
REPLY_CONTENT VARCHAR2(400) NOT NULL,
REPLY_DATE DATE DEFAULT SYSDATE NOT NULL,
REPLY_DELETE VARCHAR2(1) DEFAULT 'N' NOT NULL
);

COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글 번호';
COMMENT ON COLUMN REPLY.BOARD_NO IS '게시글 번호';
COMMENT ON COLUMN REPLY.USER_NO IS '작성자';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '내용';
COMMENT ON COLUMN REPLY.REPLY_DATE IS '작성일';
COMMENT ON COLUMN REPLY.REPLY_DELETE IS '삭제 여부';

CREATE TABLE NOTIFICATION (
NOTIFICATION_NO NUMBER PRIMARY KEY,
NOTI_CD_NO NUMBER NOT NULL,
USER_NO NUMBER NOT NULL,
MESSAGE VARCHAR2(200),
IS_READ VARCHAR2(1) DEFAULT 'N' NOT NULL,
CREATE_AT DATE DEFAULT SYSDATE NOT NULL
);

COMMENT ON COLUMN NOTIFICATION.NOTIFICATION_NO IS '알림 번호';
COMMENT ON COLUMN NOTIFICATION.NOTI_CD_NO IS '알림 유형';
COMMENT ON COLUMN NOTIFICATION.USER_NO IS '사용자';
COMMENT ON COLUMN NOTIFICATION.MESSAGE IS '메시지';
COMMENT ON COLUMN NOTIFICATION.IS_READ IS '읽음 여부';
COMMENT ON COLUMN NOTIFICATION.CREATE_AT IS '생성일';

CREATE TABLE REPORT (
REPORT_NO NUMBER PRIMARY KEY,
USER_NO NUMBER NOT NULL,
REPORT_CD_NO NUMBER NOT NULL,
TARGET_TYPE VARCHAR2(10) NOT NULL,
TARGET_NO NUMBER NOT NULL,
STATUS VARCHAR2(1) DEFAULT 'N' NOT NULL,
CREATED_AT DATE DEFAULT SYSDATE NOT NULL
);

COMMENT ON COLUMN REPORT.REPORT_NO IS '신고 번호';
COMMENT ON COLUMN REPORT.USER_NO IS '신고자';
COMMENT ON COLUMN REPORT.REPORT_CD_NO IS '신고 유형';
COMMENT ON COLUMN REPORT.TARGET_TYPE IS '대상 타입';
COMMENT ON COLUMN REPORT.TARGET_NO IS '대상 번호';
COMMENT ON COLUMN REPORT.STATUS IS '처리 상태';
COMMENT ON COLUMN REPORT.CREATED_AT IS '생성일';

CREATE TABLE USER_SANCTION (
SANCTION_NO NUMBER PRIMARY KEY,
USER_NO NUMBER NOT NULL,
SANCTIONED_AT DATE DEFAULT SYSDATE NOT NULL
);

COMMENT ON COLUMN USER_SANCTION.SANCTION_NO IS '제재 번호';
COMMENT ON COLUMN USER_SANCTION.USER_NO IS '회원 번호';
COMMENT ON COLUMN USER_SANCTION.SANCTIONED_AT IS '제재일';

CREATE TABLE WISHLIST (
USER_NO NUMBER NOT NULL,
ITEM_NO NUMBER NOT NULL,
PRIMARY KEY (USER_NO, ITEM_NO)
);

COMMENT ON COLUMN WISHLIST.USER_NO IS '회원 번호';
COMMENT ON COLUMN WISHLIST.ITEM_NO IS '상품 번호';

-- =====================================================
-- FK
-- =====================================================

ALTER TABLE MEMBER ADD CONSTRAINT FK_MEMBER_AUTH FOREIGN KEY (AUTHORITY) REFERENCES AUTHORITIES(AUTHORITY);
ALTER TABLE ITEM ADD CONSTRAINT FK_ITEM_USER FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO);
ALTER TABLE ITEM ADD CONSTRAINT FK_ITEM_CATEGORY FOREIGN KEY (ITEM_CD_NO) REFERENCES ITEM_CD(ITEM_CATEGORY_NO);
ALTER TABLE ITEM ADD CONSTRAINT FK_ITEM_COUNTRY FOREIGN KEY (COUNTRY_NO) REFERENCES COUNTRY(COUNTRY_NO);
ALTER TABLE ITEM_IMG ADD CONSTRAINT FK_ITEMIMG_ITEM FOREIGN KEY (ITEM_NO) REFERENCES ITEM(ITEM_NO);
ALTER TABLE BID ADD CONSTRAINT FK_BID_ITEM FOREIGN KEY (ITEM_NO) REFERENCES ITEM(ITEM_NO);
ALTER TABLE BID ADD CONSTRAINT FK_BID_USER FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO);
ALTER TABLE RESULT ADD CONSTRAINT FK_RESULT_BID FOREIGN KEY (BID_NO) REFERENCES BID(BID_NO);
ALTER TABLE PAYMENT ADD CONSTRAINT FK_PAYMENT_RESULT FOREIGN KEY (RESULT_NO) REFERENCES RESULT(RESULT_NO);
ALTER TABLE DELIVERY ADD CONSTRAINT FK_DELIVERY_PAYMENT FOREIGN KEY (PAYMENT_NO) REFERENCES PAYMENT(PAYMENT_NO);
ALTER TABLE DELIVERY_DETAIL ADD CONSTRAINT FK_DELIVERY_DETAIL FOREIGN KEY (DELIVERY_NO) REFERENCES DELIVERY(DELIVERY_NO);
ALTER TABLE BOARD_POST ADD CONSTRAINT FK_BOARD_USER FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO);
ALTER TABLE REPLY ADD CONSTRAINT FK_REPLY_BOARD FOREIGN KEY (BOARD_NO) REFERENCES BOARD_POST(BOARD_NO);
ALTER TABLE REPLY ADD CONSTRAINT FK_REPLY_USER FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO);
ALTER TABLE NOTIFICATION ADD CONSTRAINT FK_NOTI_USER FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO);
ALTER TABLE REPORT ADD CONSTRAINT FK_REPORT_USER FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO);
ALTER TABLE WISHLIST ADD CONSTRAINT FK_WISH_USER FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO);
ALTER TABLE WISHLIST ADD CONSTRAINT FK_WISH_ITEM FOREIGN KEY (ITEM_NO) REFERENCES ITEM(ITEM_NO);

-- =====================================================
-- CHECK
-- =====================================================

ALTER TABLE ITEM ADD CONSTRAINT CHK_ITEM_STATUS CHECK (STATUS IN ('Y','N','E'));
ALTER TABLE ITEM ADD CONSTRAINT CHK_DIRECT_BUY CHECK (DIRECT_BUY IN ('Y','N'));
ALTER TABLE MEMBER ADD CONSTRAINT CHK_MEMBER_DELETE CHECK (USER_DELETE_YN IN ('Y','N'));
ALTER TABLE NOTIFICATION ADD CONSTRAINT CHK_NOTI_READ CHECK (IS_READ IN ('Y','N'));
ALTER TABLE REPORT ADD CONSTRAINT CHK_REPORT_STATUS CHECK (STATUS IN ('Y','N'));